### ISSUE TITLE
Autoplay not working

### ISSUE THREAD

**Issue by tisnatch** [mykle1/MMM-ISS-Live#1]
Hi,
Just installed it and have been trying to get it working. The module loads but it won't autoplay. It will only play if I click the play button with the mouse. I see that autoplay is in the URL so it seems like it should work, but it's not for me. Any ideas?

**Comment by mykle1** [comment]
Starting with one of the newer electron builds, (and chrome, and mozilla) they have implemented a new 'no autoplay’ policy. Not great for MagicMirror.
However, there is a workaround. I had to use it myself. Here it is.

Edit mm/js/electron.js file

Change the code like this (at about line 20 of the file)

function createWindow() {
    app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');  //< -------- added
    var electronOptionsDefaults = {

then restart MM… autoplay will work now

This is expected to be corrected in an update to MagicMirror. They are aware of the problem
