### ISSUE TITLE
Video Laggy, possible solutions, ISS-EARTH also

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-ISS-Live#4]
Im not sure if theres a way to do this because im new to programming but having the videos at the highest or auto quality makes them choppy, being able to set them to 720p or lower would be great, ive been looking at how to do this but it seems complicated

**Comment by mykle1** [comment]
The feed is unchangeable. try using these in your config entry, or smaller:
height:"270px",
width:"480px",
